const QUOTES = [
  "El único mal entrenamiento es el que no hiciste.",
  "Tu cuerpo puede hacerlo. Convence a tu mente.",
  "No pares cuando estés cansado. Para cuando hayas terminado.",
  "El dolor de hoy es la fuerza de mañana.",
  "Cada repetición te acerca más a quien quieres ser.",
  "El éxito empieza con la decisión de intentarlo.",
  "No se trata de tener tiempo, se trata de hacer tiempo.",
  "La disciplina es el puente entre metas y logros.",
  "Un cuerpo fuerte construye una mente fuerte.",
  "Entrena duro, come bien, descansa mejor.",
  "El sudor es la grasa llorando.",
  "Tu única competencia eres tú de ayer.",
  "Haz hoy lo que otros no harán para tener mañana lo que otros no tendrán.",
  "El cuerpo logra lo que la mente cree.",
  "Sé más fuerte que tu excusa más fuerte.",
  "La constancia vence al talento cuando el talento no es constante.",
  "Cada día que entrenas es un día que inviertes en ti.",
  "No desees que fuera más fácil, desea ser más fuerte.",
  "El progreso no siempre se ve, pero siempre se construye.",
  "Un año de entrenos cambia tu cuerpo. Una vida de entrenos cambia tu destino.",
  "Lo que no te reta no te cambia.",
  "La motivación te pone en marcha. El hábito te mantiene en movimiento.",
  "Los límites existen solo en tu mente.",
  "Levántate, entrena, triunfa. Repite.",
  "El mejor momento para empezar era ayer. El segundo mejor es ahora.",
  "Cuida tu cuerpo — es el único lugar donde tienes que vivir.",
  "Fuerza no es lo que puedes hacer. Es superar lo que pensabas que no podías.",
  "Tu cuerpo es tu templo. Mantenlo sagrado.",
  "Cada gota de sudor cuenta.",
  "El fitness no es una temporada, es un estilo de vida.",
  "Transforma el 'no puedo' en 'todavía no puedo… pero lo lograré'.",
  "Pequeños progresos siguen siendo progresos.",
  "El dolor es temporal. El orgullo de rendirse es para siempre.",
  "No esperes a estar motivado. Muévete y la motivación vendrá.",
  "El cuerpo que tienes es el resultado de lo que has hecho. El cuerpo que quieres es el resultado de lo que harás.",
  "Eres más fuerte de lo que crees.",
  "Entrena como si no hubiera mañana, vive como si hubiera muchos.",
  "La salud es la mayor riqueza que puedes tener.",
  "Ganar no siempre significa ser el primero. Ganar es superar tus miedos.",
  "No es sobre ser el mejor del mundo. Es sobre ser mejor que ayer.",
  "Tu esfuerzo de hoy construye tu fortaleza de mañana.",
  "El fitness empieza en la cabeza.",
  "Cada entrenamiento es un escalón hacia tu mejor versión.",
  "Si el plan no funciona, cambia el plan, no la meta.",
  "El que mueve montañas empieza por mover piedras pequeñas.",
  "Confía en el proceso aunque no veas los resultados todavía.",
  "El trabajo duro late al talento cuando el talento no trabaja duro.",
  "Una hora de ejercicio es el 4% de tu día. Sin excusas.",
  "Cuanto más sudes en el entrenamiento, menos sangrarás en la batalla.",
  "La resistencia no viene de las capacidades físicas, viene de un espíritu indomable.",
  "Hoy es otro día para ser mejor.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "No cuentes los días, haz que los días cuenten.",
  "El cuerpo logra lo que la mente ordena.",
  "La única forma de fracasar es dejar de intentarlo.",
  "Siente el dolor del esfuerzo o el dolor del arrepentimiento.",
  "Los grandes cuerpos se construyen en los momentos en que no tienes ganas.",
  "Nunca te arrepentirás de un entrenamiento.",
  "Lo imposible es solo aquello que no se ha intentado todavía.",
  "Si piensas que puedes, ya estás a medio camino.",
  "El movimiento es medicina para crear un cambio físico, emocional y mental.",
  "Entrena tu mente igual que tu cuerpo.",
  "No te compares con otros. Compárate con quien eras ayer.",
  "Cada kilómetro recorrido es un kilómetro que no recorrió nadie por ti.",
  "La diferencia entre un buen día y un mal día es tu actitud.",
  "Lo que duerme no avanza. Lo que entrena, crece.",
  "Haz que valga la pena el tiempo que inviertes en ti.",
  "Rodéate de personas que te impulsen a superarte.",
  "La fuerza no viene de ganar. Viene de las luchas que superas.",
  "Sé el tipo de persona que completa lo que empieza.",
  "Tu salud es una inversión, no un gasto.",
  "Si el cuerpo dice para, la mente dice una más.",
  "Cada mañana que entrenas es una victoria antes del desayuno.",
  "Los resultados no llegan con suerte, llegan con sudor.",
  "Un músculo no se construye en un día, pero tampoco sin entrenar cada día.",
  "La perseverancia es el camino hacia el éxito.",
  "Hazlo aunque no tengas ganas. Especialmente cuando no tengas ganas.",
  "El entrenamiento de hoy es el bienestar de mañana.",
  "Tu cuerpo escucha todo lo que tu mente dice.",
  "No hay elevador hacia el éxito. Hay que tomar las escaleras.",
  "La salud no es todo, pero sin ella todo lo demás es nada.",
  "Nunca es demasiado tarde para empezar a cuidarte.",
  "Empieza donde estás. Usa lo que tienes. Haz lo que puedes.",
  "El secreto del éxito es la constancia en el propósito.",
  "La disciplina es elegir entre lo que quieres ahora y lo que quieres más.",
  "No busques el camino fácil. Busca el que te haga más fuerte.",
  "Un cuerpo en movimiento permanece en movimiento.",
  "Cuida tus hábitos porque se convierten en tu carácter.",
  "El día que empieces a amarte también empezarás a moverte.",
  "Sé constante. Los resultados llegarán.",
  "Los guerreros no nacen, se forjan en el entrenamiento.",
  "Tu actitud determina tu altitud.",
  "La mente manda. El cuerpo obedece.",
  "Cada repetición que haces cuando ya no quieres es la que más cuenta.",
  "Mueve tu cuerpo y cambia tu vida.",
  "Nunca subestimes el poder de un entrenamiento diario.",
  "Los campeones siguen jugando hasta que lo hacen bien.",
  "La fortaleza física alimenta la fortaleza mental.",
  "Si no cuidas tu cuerpo ahora, tendrás que cuidarlo cuando enferme.",
  "Un entrenamiento que te desafía te cambia.",
  "Los mejores resultados requieren los mejores esfuerzos.",
  "Cada sesión de entrenamiento es un regalo que te haces a ti mismo.",
  "No busques tiempo. Crea tiempo.",
  "El mayor obstáculo eres tú mismo.",
  "Suda ahora. Brilla después.",
  "La fuerza de voluntad es un músculo. Cuanto más la uses, más fuerte se vuelve.",
  "El éxito no es siempre lo que ves, sino lo que sientes al esforzarte.",
  "Ser activo no es un castigo, es un privilegio.",
  "Tu cuerpo es una obra de arte que tú esculpes.",
  "Cada paso cuenta. Cada repetición importa.",
  "La mejora continua es mejor que la perfección postergada.",
  "No pares hasta que estés orgulloso.",
  "Si te rindes hoy, tendrás que empezar otra vez mañana.",
  "El dolor de la disciplina siempre es menor que el dolor del arrepentimiento.",
  "Nadie se arrepintió nunca de haber ido al gimnasio.",
  "La energía fluye donde la atención va.",
  "Haz de tu entrenamiento una cita contigo mismo que nunca cancelas.",
  "Un cuerpo fuerte empieza con una mente fuerte.",
  "La salud es el primer paso hacia todo lo demás.",
  "Tus excusas tienen tan poca fuerza como tú decides darles.",
  "Si puedes soñarlo, puedes entrenarlo.",
  "Convierte el miedo en combustible.",
  "El entrenamiento no es un sacrificio, es una inversión.",
  "Cuando quieras rendirte, recuerda por qué empezaste.",
  "El camino más largo empieza con un solo paso.",
  "Nunca te arrepentirás de haber sido demasiado sano.",
  "La persistencia puede cambiar el fracaso en logro extraordinario.",
  "Haz algo hoy que tu yo del futuro te agradezca.",
  "El esfuerzo de hoy es el éxito de mañana.",
  "No te quedes cómodo donde estás si no es donde quieres estar.",
  "Cada entrenamiento completado es una promesa cumplida a ti mismo.",
  "Si te duele, mejora. Si no te duele, trabaja más.",
  "El cuerpo humano es increíble. Deja que haga lo que fue diseñado para hacer.",
  "La salud es una corona que solo los enfermos pueden ver.",
  "Transforma tu rutina en ritual.",
  "El movimiento es la medicina más antigua del mundo.",
  "Muévete más. Quéjate menos.",
  "Una buena sesión de entrenamiento puede cambiar todo tu día.",
  "No es quien eres lo que te frena. Es quien piensas que no eres.",
  "Los hábitos saludables hoy son la libertad de mañana.",
  "Haz del descanso una parte de tu entrenamiento, no una excusa.",
  "El cuerpo recuerda cada entrenamiento aunque tú lo hayas olvidado.",
  "El límite que ves es el límite que crees.",
  "Eres lo que repites. Haz que valga la pena repetirlo.",
  "Entrenar no es solo mover el cuerpo, es nutrir el alma.",
  "El fitness es matemática simple: esfuerzo más constancia igual a resultados.",
  "La grandeza no se regala. Se gana.",
  "Si te parece imposible, es porque aún no lo has intentado suficiente.",
  "Cada entrenamiento te hace un poco mejor de lo que eras.",
  "Mueve el cuerpo. Despeja la mente.",
  "No es sobre ser perfecto. Es sobre ser mejor.",
  "El desafío de hoy es el logro de mañana.",
  "Decide. Comprométete. Triunfa.",
  "Los resultados tardan. La constancia los acelera.",
  "Tu cuerpo es el reflejo de tu estilo de vida.",
  "Empieza bien el día con movimiento y el resto fluirá.",
  "Lo que te propones, lo consigues. Proponte estar sano.",
  "La forma física no es un destino. Es un viaje sin fin.",
  "El que entrena en la tormenta llega brillando al sol.",
  "No hay atajos para ningún lugar que valga la pena ir.",
  "El esfuerzo nunca miente.",
  "Sé el arquero de tu propia vida. Apunta siempre alto.",
  "Haz del ejercicio tu terapia más barata y efectiva.",
  "Cada músculo que desarrollas es una historia de superación.",
  "La energía que gastas en el gym la ganarás en vida.",
  "La fuerza se construye en los momentos más difíciles.",
  "Tu salud es tu responsabilidad. Nadie más puede cuidarla por ti.",
  "El fitness no tiene fin. Siempre hay un nivel más.",
  "No busques que sea fácil. Busca que valga la pena.",
  "El que no avanza, retrocede.",
  "Cada serie que terminas dice más de ti que mil palabras.",
  "La excelencia es una elección diaria.",
  "Muévete por amor propio, no por miedo.",
  "El deporte es el antídoto para la pereza y la tristeza.",
  "Respeta tu cuerpo. Trabájalo. Aliméntalo bien.",
  "Si tu cuerpo es tu templo, entrena como si fuera sagrado.",
  "No necesitas ser extremo, solo consistente.",
  "La disciplina de hoy crea la libertad de mañana.",
  "Un entrenamiento a tiempo vale más que mil excusas.",
  "Sé el héroe de tu propia historia.",
  "El fitness te enseña que puedes con más de lo que creías.",
  "Hoy es el día perfecto para ser mejor que ayer.",
  "Tu bienestar es tu mejor inversión.",
  "Supérate a ti mismo. Es la única competencia que importa.",
  "Cada meta grande empieza con la decisión pequeña de empezar.",
  "La constancia es el arma secreta de los que logran sus metas.",
  "Suda, sonríe, repite.",
  "El deporte enseña lo que ningún libro puede.",
  "Haz que tu entrenamiento sea el mejor momento del día.",
  "Los que llegan lejos empiezan por dar el primer paso.",
  "La vida es corta. Vívela activo.",
  "El movimiento es alegría. Quédate quieto y verás.",
  "Cada kilo menos es un kilo de esfuerzo materializado.",
  "No te juzgues por donde estás, sino por hacia dónde vas.",
  "El tiempo que inviertes en ti siempre rinde beneficios.",
  "La mejor versión de ti te está esperando al otro lado del esfuerzo.",
  "Haz del bienestar una prioridad, no una opción.",
  "El músculo que no usas lo pierde quien lo trabaja.",
  "Tu cuerpo vale más que cualquier excusa que tengas.",
  "La fortaleza se construye con años. El abandono, en segundos.",
  "La mente que se rinde primero pierde. Entrena también la mente.",
  "Un día a la vez. Un rep a la vez.",
  "No te conformes con menos de lo que puedes ser.",
  "La comida es combustible. El entrenamiento es el motor.",
  "El estilo de vida activo no es una moda, es una necesidad.",
  "Cuida tus músculos hoy para moverte libre mañana.",
  "La inercia del movimiento es la mayor aliada del atleta.",
  "Sal de tu zona de confort y entra en tu zona de crecimiento.",
  "El cuerpo se adapta. La mente también. Entrena ambos.",
  "No hay excusa que valga más que tu salud.",
  "Los sueños no funcionan a menos que tú lo hagas.",
  "Sé la persona que no necesita motivación para entrenar.",
  "Muévete aunque sea despacio. Lo lento también avanza.",
  "No hay mal humor que un buen entrenamiento no cure.",
  "El deporte te da lo que nadie más puede darte.",
  "Ponerse la ropa de entrenamiento ya es la mitad del camino.",
  "Haz de la constancia tu superpoder.",
  "Tu energía aumenta cuando tu cuerpo se mueve.",
  "Alimenta tu ambición, no tu pereza.",
  "El ejercicio es un regalo que te haces en el presente para el futuro.",
  "Entrena fuerte o entrena largo. Pero entrena.",
  "La fortaleza no es física, es mental.",
  "Lo que haces cada día importa más que lo que haces de vez en cuando.",
  "Haz del hábito más grande que de la motivación.",
  "Ningún esfuerzo se pierde. Todo suma.",
  "Tu cuerpo responde a lo que le exiges. Exígele más.",
  "Empuja hasta que no puedas, descansa, empuja de nuevo.",
  "Cuanto más te cuidas, más puedes dar a los demás.",
  "El deporte es igualdad: todos empezamos desde cero.",
  "La salud mental empieza en el movimiento del cuerpo.",
  "Cuando la pereza hable, que hable más fuerte tu voluntad.",
  "El músculo que más debes entrenar es el corazón.",
  "Nadie te puede dar la forma física. Tienes que ganártela.",
  "Entrena como si dependiera de ello. Porque depende.",
  "El que entrena en silencio hace ruido con sus resultados.",
  "Un día sin movimiento es un día regalado al tiempo.",
  "No temas al dolor. Teme a quien no lo intenta.",
  "La rutina saludable es la mejor rutina que puedes tener.",
  "Si quieres algo que nunca has tenido, haz algo que nunca has hecho.",
  "El deporte enseña que los límites se superan, no se aceptan.",
  "Lo que siembras en el gimnasio lo cosechas en la vida.",
  "Vive activo, muere sano.",
  "Cada flexión te hace más flexible de lo que eras.",
  "El cuerpo recuerda el sacrificio aunque la mente lo olvide.",
  "No hay resultados sin esfuerzo. No hay esfuerzo sin decisión.",
  "La forma en que entrenas es la forma en que vives.",
  "Tu cuerpo es tu inversión más rentable.",
  "Cuando el cuerpo quiere parar, el alma dice una más.",
  "Los mejores momentos del día están en el entrenamiento.",
  "Haz de la salud tu religión.",
  "La fuerza interior se refleja en la fuerza exterior.",
  "Si no es ahora, ¿cuándo?",
  "Corre hacia tu mejor versión.",
  "Un cuerpo activo es un cuerpo feliz.",
  "Sé el cambio que quieres ver en tu espejo.",
  "El deporte une cuerpo, mente y espíritu.",
  "Cada vez que eliges entrenar, eliges tu mejor yo.",
  "La resistencia se construye en los momentos más duros.",
  "Tu cuerpo es tuyo. Trátalo como el tesoro que es.",
  "Los que se rinden nunca saben lo cerca que estaban.",
  "Hacer ejercicio no es castigo para tu cuerpo, es un regalo.",
  "Mañana te alegrarás de haber entrenado hoy.",
  "El movimiento que haces hoy te mantiene en pie mañana.",
  "Haz del bienestar un compromiso, no un capricho.",
  "No esperes sentirte listo. Empieza y te sentirás listo.",
  "La vida activa es la vida que vale la pena vivir.",
  "Pon tu corazón en cada repetición.",
  "Cada serie superada es un paso más hacia quien quieres ser.",
  "La salud no se improvisa, se construye cada día.",
  "Gana la batalla de la mañana y habrás ganado el día.",
  "Hazlo con pasión o no lo hagas.",
  "El peso que levantas hoy aligera la carga de mañana.",
  "Tu cuerpo es un arma. Afílala cada día.",
  "La victoria más grande es vencerte a ti mismo.",
  "El que avanza aunque le cueste llega más lejos que el que no sale.",
  "Una mente activa necesita un cuerpo activo.",
  "Lo que haces en el gimnasio se nota fuera de él.",
  "Los grandes resultados exigen grandes sacrificios.",
  "Nunca subestimes lo que tu cuerpo puede hacer.",
  "La salud es la base de todo lo demás que quieres construir.",
  "Eres más capaz de lo que crees. Demuéstratelo.",
  "Sé disciplinado cuando no tengas ganas y serás imparable.",
  "El ejercicio es la clave maestra de la salud.",
  "Haz del movimiento tu estado natural.",
  "La satisfacción del esfuerzo no tiene precio.",
  "Un cuerpo bien entrenado lleva una mente bien templada.",
  "El mayor regalo que puedes hacerte es cuidar tu salud.",
  "Entrena tu cuerpo. Libera tu mente.",
  "No hay secreto. Solo trabajo, constancia y paciencia.",
  "El fitness es un estilo de vida que vale para siempre.",
  "Suda las penas. Levanta las pesas. Vive mejor.",
  "El cuerpo es sabio. Si lo tratas bien, te lo devuelve con creces.",
  "El que descansa demasiado, oxida.",
  "Cada entrenamiento es una carta de amor a tu cuerpo.",
  "La mejor droga es el ejercicio. Legal, gratuita y efectiva.",
  "No te pongas límites que la vida no te ha puesto.",
  "El músculo más importante que puedes desarrollar es el hábito.",
  "Entrena por amor a tu vida, no por miedo a tu cuerpo.",
  "Las victorias silenciosas son las más poderosas.",
  "Si no te superas, te estancas.",
  "El sacrificio de hoy es el lujo de mañana.",
  "La constancia es la madre de todos los logros.",
  "Haz que el ejercicio sea parte de tu ADN.",
  "Tu voluntad es más fuerte que cualquier obstáculo.",
  "El esfuerzo siempre tiene recompensa. A veces tarda, pero llega.",
  "Cada día activo es un día ganado.",
  "Lo que el cuerpo logra, la mente primero lo creyó.",
  "Pon a prueba tus límites. Descubrirás que no existen.",
  "La fortaleza física es fortaleza de carácter.",
  "Vive saludablemente para vivir plenamente.",
  "El que cuida su cuerpo cuida su futuro.",
  "Muévete. Tu cuerpo te lo pedirá.",
  "Decide hoy quién quieres ser mañana.",
  "El deporte no tiene edad. Tiene actitud.",
  "Sé tu propio entrenador personal.",
  "Lo que hoy parece difícil, mañana será tu calentamiento.",
  "El fitness es la inversión con mayor retorno de la vida.",
  "Cuida tu salud como si no hubiera un plan B.",
  "Los resultados llegan para los que no se rinden.",
  "Cada rep, cada serie, cada sesión te hace mejor.",
  "La salud no se negocia.",
  "Hazlo hoy con esfuerzo o mañana con vergüenza.",
  "La vida activa es la vida más plena.",
  "No esperes el lunes. Empieza ahora.",
  "El que trabaja en silencio obtiene resultados que hablan.",
  "Avanza aunque sea despacio. Lo importante es no parar.",
  "Los hábitos saludables no se heredan, se eligen.",
  "Un cuerpo bien nutrido y bien ejercitado es un cuerpo libre.",
  "La perseverancia del atleta inspira al mundo.",
  "Cuando te canses de empezar, habrás terminado de rendirte.",
  "El trabajo constante supera al genio ocasional.",
  "Tu mayor logro deportivo siempre está en el siguiente entrenamiento.",
  "El deporte enseña que los límites son mentales.",
  "No des excusas. Da resultados.",
  "La salud es el combustible de todos tus sueños.",
  "Haz que cada entrenamiento cuente.",
  "La mente que se entrena no conoce el imposible.",
  "Un cuerpo en forma es un cuerpo que dice sí a la vida.",
  "No se trata de perfectión. Se trata de progreso.",
  "El esfuerzo es el precio de la excelencia.",
  "Cada músculo que duele hoy es un músculo que crece mañana.",
  "Hazlo con energía o descansa y vuelve con más.",
  "El entrenamiento diario es la respuesta a muchas preguntas de salud.",
  "Tu cuerpo puede más de lo que tu mente le permite.",
  "La actividad física es la mejor medicina preventiva.",
  "Haz del movimiento tu modo de vida.",
  "Sé la persona que va al entrenamiento aunque llueva.",
  "Tu cuerpo escribe la historia de tus elecciones.",
  "Un entrenamiento fuerte construye un carácter fuerte.",
  "Los que más han logrado, más han entrenado.",
  "Haz del sudor tu firma diaria.",
  "El que cuida su cuerpo cuida su mente y su alma.",
  "La salud es riqueza que ningún banco puede guardar.",
  "Tu cuerpo responde a la atención que le das.",
  "Empieza donde puedas. Mejora donde debas.",
  "La diferencia entre atleta y sedentario es una decisión diaria.",
  "Haz del ejercicio algo que no puedas dejar de hacer.",
  "La vida es movimiento. El movimiento es vida.",
  "Tu mejor entrenamiento todavía no ha pasado.",
  "Haz lo difícil ahora para que lo fácil llegue después.",
  "Entrena la mente para entrenar el cuerpo.",
  "El que no cuida su salud regala su tiempo a la enfermedad.",
  "Haz del bienestar tu superpoder cotidiano.",
  "Cada rep que completas es una victoria pequeña.",
  "No se trata de cuánto pesas, sino de cuánto puedes.",
  "La fuerza se mide en voluntad, no en kilos.",
  "Haz del entrenamiento tu mejor hábito.",
  "Los minutos de entrenamiento son inversión, no pérdida de tiempo.",
  "Sé consistente con tu cuerpo y él será consistente contigo.",
  "El bienestar no llega solo. Hay que buscarlo cada día.",
  "Tu salud vale más que cualquier excusa.",
  "La transformación comienza cuando la excusa termina.",
  "Entrena con propósito. Vive con energía.",
  "No hay límite para quien decide no tenerlo.",
  "El deporte transforma el cuerpo y libera el espíritu.",
  "Haz de tu cuerpo tu mejor proyecto.",
  "La fortaleza que construyes en el gym, la usas en la vida.",
  "No renuncies a lo que más quieres por lo que quieres en este momento.",
  "La salud activa es la base de una vida plena.",
  "Tu cuerpo te lleva a todos tus sueños. Cuídalo.",
  "Sé constante, sé fuerte, sé imparable.",
  "El entrenamiento de hoy es el beneficio de mañana.",
]

export function getQuoteOfDay() {
  const start = new Date(2026, 0, 1)
  const today = new Date()
  const dayOfYear = Math.floor((today - start) / (1000 * 60 * 60 * 24))
  return QUOTES[Math.abs(dayOfYear) % QUOTES.length]
}
